### ISSUE TITLE
Colon is bad character in url?!

### ISSUE THREAD

**Issue by Gared** [ether/ep_hide_referrer#9]
When I try to open a link with a colon in it I get the message "bad url - posssible XSS attempt"

**Comment by thedod** [comment]
Ouch. On closer inspection, the regex I [picked](https://github.com/component/regexps/blob/master/index.js#L3) up last time (saw it at stackexchange or something) isn't very good (even seems to be uk-centric). IMHO we need something primitive that allows http[s]://whatever because all we want is to avoid shady protocols like javascript: and device-specific ones (camera, phone). OTOH, no reason to treat `.onion` URLS badly (d'Oh).

Since the entire URL is visible, other attacks are unlikely: if someone crafts a very long URL that goes to localhost and injects something long with lots of %XX in it - a sane user would know not to click such a monstrosity (I hope).

Unless anyone objects (@JohnMcLear?), let's dumb this down to the max.

**Comment by JohnMcLear** [comment]
no objections

**Comment by wrought** [comment]
Is there a pull request associated with this change? 

Instead, you could use a library such as: https://github.com/joyent/node/blob/master/lib/url.js

**Comment by wrought** [comment]
I submitted a pull request here: https://github.com/JohnMcLear/ep_hide_referrer/pull/12

**Comment by rohieb** [comment]
> IMHO we need something primitive that allows http[s]://whatever because all we want is to avoid shady protocols like javascript: and device-specific ones (camera, phone). 

Yeah, I vote for that too. The current regexp also does not match several newly allocated (internationalized) TLDs, or valid URLs with urlencoded characters in them (like Wikipedia articles in any language which uses a different charset than US-ASCII). And to be fair, I don't think anyone has the slightest clue how that 568-character regex really works.

For this reason, I have implemented a whitelist of well-known URI schemes in #16. If the provided URL hash does not match those schemes, the URL is presented to the user with a warning, but they can still click the URL. After all, there are [various URI schemes](https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml) on the web, some of them are possibly "unsafe", some "safe", we cannot know them all, but we also don't want to restrict the user in case of false positives. So let's solve the problem for the simple cases, and for others, the users should be able to decide by themselves after reading the warning.

The code from #16 is deployed on my server (together with the code from #11, which I find very useful), I have some test cases in https://pad.stratum0.org/p/urltests.

**Comment by rohieb** [comment]
FYI, this issue should be resolved since #16 was merged.
